### PR TITLE
Ignore file extension case, upgrade asset pipeline plugins

### PR DESCRIPTION
**Pull request by dustindclark**

### CODE REVIEW

**Comment by dustindclark** [comment]
@4np - is there anything that I can do to get this reviewed/approved/published?  Thanks.

**Comment by asoftwareguy** [comment]
@4np how can we get a new version published to the plugin portal with this fix?

**Comment by dustindclark** [comment]
@4np , any updates?  We've been waiting on this to be published since June.

**Comment by 4np** [comment]
Dustin, 

I have abandoned the plugin. I haven't been doing Grails for over 3 years now and I am currently doing fulltime iOS development. I was trying to push out a last release containing the merged code, but ```Grails``` won't even run anymore without throwing exceptions.

If you're interested in taking over, feel free to fork. 

Cheers, Jeroen

**Comment by asoftwareguy** [comment]
@4np I don't mind forking the repo and continuing on from there, but I want to ask first, would you consider transferring the ownership of the Uploadr repos to either myself or Dustin? That way, the complete history of the project is retained, issues are transferred, etc.
https://help.github.com/articles/transferring-a-repository/

**Comment by dustindclark** [comment]
@4np , I have forked (https://github.com/dustindclark/grails-uploadr), and updated the version.  If you could transfer the ownership so that I can get the latest version published, I'd appreciate it.  Thanks.

**Comment by 4np** [comment]
Hi Dustin,

I noticed you already updated the [plugin page](https://grails.org/plugin/uploadr) to point to your forked repo, so I suspect you should already be able to push a new update?

**Comment by dustindclark** [comment]
Yes, thank you.  I requested permission, and the latest version has been published from the fork.  I’ve also added some unit tests…hope to add more sometime soon.

Thanks again.

Dustin

**Comment by 4np** [comment]
Allright, good to hear :+1:  Thanks for taking over, and happy holidays :+1:

**Pull request merged**
